### ISSUE TITLE
Need for review and audit

### ISSUE THREAD

**Issue by 12347799** [krptn/krypton#173]
One of the things I find problematic, with this otherwise very interesting project, is the lack of existing reviews.

Because this project doesn't have a large user base, many people may feel it to be risky to use. If a reputable third party reviewed this project, and found it to be secure and reliable, I think many more people would start using it.

I don't know how such would be possible but I strongly encourage maintainers to look into it. 

Looking forward to seeing this develop!

**Comment by MBS9Admin** [comment]
Welcome to Krptn! We are glad to see you. *Note:* any code submited is done so under our license - please read it. Your issue will shortly be viewed by a human.

**Comment by MBS9** [comment]
Hey @12347799!

I totally agree with you regarding the need for review and audit. 

Since our software has features to store very sensitive data, we understand that users would like to see a guarantee that it will be secure. We understand the risks that people take by using a not-so-popular project for sensitive data. 

If anyone has any review or experience with this IAM, it would be much beneficial for them to submit it. We could use it for many purposes such as building trust, improving quality and security. People can either email us at [contact@krptn.dev](mailto:contact@krptn.dev), put it in a GitHub discussion, or paste it into this issue!

**Comment by MBS9Admin** [comment]
Closing issue in 7 days, this is a stale issue.

**Comment by MBS9Admin** [comment]
Closed due to inactivity.
